var languages_iso_639 = [
 {
    "blank": 0,
    "Language family": "Northwest Caucasian",
    "Language name": "Abkhaz",
    "Native name": "аҧсуа бызшәа, аҧсшәа",
    "639‑1": "ab",
    "639‑2/T": "abk",
    "639‑2/B": "abk",
    "639‑3": "abk",
    "639‑6": "abks",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Afro-Asiatic",
    "Language name": "Afar",
    "Native name": "Afaraf",
    "639‑1": "aa",
    "639‑2/T": "aar",
    "639‑2/B": "aar",
    "639‑3": "aar",
    "639‑6": "aars",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Afrikaans",
    "Native name": "Afrikaans",
    "639‑1": "af",
    "639‑2/T": "afr",
    "639‑2/B": "afr",
    "639‑3": "afr",
    "639‑6": "afrs",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Akan",
    "Native name": "Akan",
    "639‑1": "ak",
    "639‑2/T": "aka",
    "639‑2/B": "aka",
    "639‑3": "aka + 2",
    "639‑6": 0,
    "Notes": "macrolanguage, Twi is [tw/twi], Fanti is [fat]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Albanian",
    "Native name": "Shqip",
    "639‑1": "sq",
    "639‑2/T": "sqi",
    "639‑2/B": "alb",
    "639‑3": "sqi + 4",
    "639‑6": 0,
    "Notes": "macrolanguage, \"Albanian Phylozone\" in 639-6",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Afro-Asiatic",
    "Language name": "Amharic",
    "Native name": "አማርኛ",
    "639‑1": "am",
    "639‑2/T": "amh",
    "639‑2/B": "amh",
    "639‑3": "amh",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Afro-Asiatic",
    "Language name": "Arabic",
    "Native name": "العربية",
    "639‑1": "ar",
    "639‑2/T": "ara",
    "639‑2/B": "ara",
    "639‑3": "ara + 30",
    "639‑6": 0,
    "Notes": "macrolanguage, Standard Arabic is [arb]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Aragonese",
    "Native name": "aragonés",
    "639‑1": "an",
    "639‑2/T": "arg",
    "639‑2/B": "arg",
    "639‑3": "arg",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Armenian",
    "Native name": "Հայերեն",
    "639‑1": "hy",
    "639‑2/T": "hye",
    "639‑2/B": "arm",
    "639‑3": "hye",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Assamese",
    "Native name": "অসমীয়া",
    "639‑1": "as",
    "639‑2/T": "asm",
    "639‑2/B": "asm",
    "639‑3": "asm",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Northeast Caucasian",
    "Language name": "Avaric",
    "Native name": "авар мацӀ, магӀарул мацӀ",
    "639‑1": "av",
    "639‑2/T": "ava",
    "639‑2/B": "ava",
    "639‑3": "ava",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Avestan",
    "Native name": "avesta",
    "639‑1": "ae",
    "639‑2/T": "ave",
    "639‑2/B": "ave",
    "639‑3": "ave",
    "639‑6": 0,
    "Notes": "ancient",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Aymaran",
    "Language name": "Aymara",
    "Native name": "aymar aru",
    "639‑1": "ay",
    "639‑2/T": "aym",
    "639‑2/B": "aym",
    "639‑3": "aym + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Azerbaijani",
    "Native name": "azərbaycan dili",
    "639‑1": "az",
    "639‑2/T": "aze",
    "639‑2/B": "aze",
    "639‑3": "aze + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Bambara",
    "Native name": "bamanankan",
    "639‑1": "bm",
    "639‑2/T": "bam",
    "639‑2/B": "bam",
    "639‑3": "bam",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Bashkir",
    "Native name": "башҡорт теле",
    "639‑1": "ba",
    "639‑2/T": "bak",
    "639‑2/B": "bak",
    "639‑3": "bak",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Language isolate",
    "Language name": "Basque",
    "Native name": "euskara, euskera",
    "639‑1": "eu",
    "639‑2/T": "eus",
    "639‑2/B": "baq",
    "639‑3": "eus",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Belarusian",
    "Native name": "беларуская мова",
    "639‑1": "be",
    "639‑2/T": "bel",
    "639‑2/B": "bel",
    "639‑3": "bel",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Bengali, Bangla",
    "Native name": "বাংলা",
    "639‑1": "bn",
    "639‑2/T": "ben",
    "639‑2/B": "ben",
    "639‑3": "ben",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Bihari",
    "Native name": "भोजपुरी",
    "639‑1": "bh",
    "639‑2/T": "bih",
    "639‑2/B": "bih",
    "639‑3": 0,
    "639‑6": 0,
    "Notes": "Collective language code for Bhojpuri, Magahi, andMaithili",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Creole",
    "Language name": "Bislama",
    "Native name": "Bislama",
    "639‑1": "bi",
    "639‑2/T": "bis",
    "639‑2/B": "bis",
    "639‑3": "bis",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Bosnian",
    "Native name": "bosanski jezik",
    "639‑1": "bs",
    "639‑2/T": "bos",
    "639‑2/B": "bos",
    "639‑3": "bos",
    "639‑6": "boss",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Breton",
    "Native name": "brezhoneg",
    "639‑1": "br",
    "639‑2/T": "bre",
    "639‑2/B": "bre",
    "639‑3": "bre",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Bulgarian",
    "Native name": "български език",
    "639‑1": "bg",
    "639‑2/T": "bul",
    "639‑2/B": "bul",
    "639‑3": "bul",
    "639‑6": "buls",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Sino-Tibetan",
    "Language name": "Burmese",
    "Native name": "ဗမာစာ",
    "639‑1": "my",
    "639‑2/T": "mya",
    "639‑2/B": "bur",
    "639‑3": "mya",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Catalan",
    "Native name": "català",
    "639‑1": "ca",
    "639‑2/T": "cat",
    "639‑2/B": "cat",
    "639‑3": "cat",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Chamorro",
    "Native name": "Chamoru",
    "639‑1": "ch",
    "639‑2/T": "cha",
    "639‑2/B": "cha",
    "639‑3": "cha",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Northeast Caucasian",
    "Language name": "Chechen",
    "Native name": "нохчийн мотт",
    "639‑1": "ce",
    "639‑2/T": "che",
    "639‑2/B": "che",
    "639‑3": "che",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Chichewa, Chewa, Nyanja",
    "Native name": "chiCheŵa, chinyanja",
    "639‑1": "ny",
    "639‑2/T": "nya",
    "639‑2/B": "nya",
    "639‑3": "nya",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Sino-Tibetan",
    "Language name": "Chinese",
    "Native name": "中文 (Zhōngwén), 汉语, 漢語",
    "639‑1": "zh",
    "639‑2/T": "zho",
    "639‑2/B": "chi",
    "639‑3": "zho +13",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Chuvash",
    "Native name": "чӑваш чӗлхи",
    "639‑1": "cv",
    "639‑2/T": "chv",
    "639‑2/B": "chv",
    "639‑3": "chv",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Cornish",
    "Native name": "Kernewek",
    "639‑1": "kw",
    "639‑2/T": "cor",
    "639‑2/B": "cor",
    "639‑3": "cor",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Corsican",
    "Native name": "corsu, lingua corsa",
    "639‑1": "co",
    "639‑2/T": "cos",
    "639‑2/B": "cos",
    "639‑3": "cos",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Algonquian",
    "Language name": "Cree",
    "Native name": "ᓀᐦᐃᔭᐍᐏᐣ",
    "639‑1": "cr",
    "639‑2/T": "cre",
    "639‑2/B": "cre",
    "639‑3": "cre + 6",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Croatian",
    "Native name": "hrvatski jezik",
    "639‑1": "hr",
    "639‑2/T": "hrv",
    "639‑2/B": "hrv",
    "639‑3": "hrv",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Czech",
    "Native name": "čeština, český jazyk",
    "639‑1": "cs",
    "639‑2/T": "ces",
    "639‑2/B": "cze",
    "639‑3": "ces",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Danish",
    "Native name": "dansk",
    "639‑1": "da",
    "639‑2/T": "dan",
    "639‑2/B": "dan",
    "639‑3": "dan",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Divehi, Dhivehi, Maldivian",
    "Native name": "ދިވެހި",
    "639‑1": "dv",
    "639‑2/T": "div",
    "639‑2/B": "div",
    "639‑3": "div",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Dutch",
    "Native name": "Nederlands, Vlaams",
    "639‑1": "nl",
    "639‑2/T": "nld",
    "639‑2/B": "dut",
    "639‑3": "nld",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Sino-Tibetan",
    "Language name": "Dzongkha",
    "Native name": "རྫོང་ཁ",
    "639‑1": "dz",
    "639‑2/T": "dzo",
    "639‑2/B": "dzo",
    "639‑3": "dzo",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "English",
    "Native name": "English",
    "639‑1": "en",
    "639‑2/T": "eng",
    "639‑2/B": "eng",
    "639‑3": "eng",
    "639‑6": "engs",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Constructed",
    "Language name": "Esperanto",
    "Native name": "Esperanto",
    "639‑1": "eo",
    "639‑2/T": "epo",
    "639‑2/B": "epo",
    "639‑3": "epo",
    "639‑6": 0,
    "Notes": "constructed, initiated from L.L. Zamenhof, 1887",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Uralic",
    "Language name": "Estonian",
    "Native name": "eesti, eesti keel",
    "639‑1": "et",
    "639‑2/T": "est",
    "639‑2/B": "est",
    "639‑3": "est + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Ewe",
    "Native name": "Eʋegbe",
    "639‑1": "ee",
    "639‑2/T": "ewe",
    "639‑2/B": "ewe",
    "639‑3": "ewe",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Faroese",
    "Native name": "føroyskt",
    "639‑1": "fo",
    "639‑2/T": "fao",
    "639‑2/B": "fao",
    "639‑3": "fao",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Fijian",
    "Native name": "vosa Vakaviti",
    "639‑1": "fj",
    "639‑2/T": "fij",
    "639‑2/B": "fij",
    "639‑3": "fij",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Uralic",
    "Language name": "Finnish",
    "Native name": "suomi, suomen kieli",
    "639‑1": "fi",
    "639‑2/T": "fin",
    "639‑2/B": "fin",
    "639‑3": "fin",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "French",
    "Native name": "français, langue française",
    "639‑1": "fr",
    "639‑2/T": "fra",
    "639‑2/B": "fre",
    "639‑3": "fra",
    "639‑6": "fras",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Fula, Fulah, Pulaar, Pular",
    "Native name": "Fulfulde, Pulaar, Pular",
    "639‑1": "ff",
    "639‑2/T": "ful",
    "639‑2/B": "ful",
    "639‑3": "ful + 9",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Galician",
    "Native name": "galego",
    "639‑1": "gl",
    "639‑2/T": "glg",
    "639‑2/B": "glg",
    "639‑3": "glg",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "South Caucasian",
    "Language name": "Georgian",
    "Native name": "ქართული",
    "639‑1": "ka",
    "639‑2/T": "kat",
    "639‑2/B": "geo",
    "639‑3": "kat",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "German",
    "Native name": "Deutsch",
    "639‑1": "de",
    "639‑2/T": "deu",
    "639‑2/B": "ger",
    "639‑3": "deu",
    "639‑6": "deus",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Greek (modern)",
    "Native name": "ελληνικά",
    "639‑1": "el",
    "639‑2/T": "ell",
    "639‑2/B": "gre",
    "639‑3": "ell",
    "639‑6": "ells",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Tupian",
    "Language name": "Guaraní",
    "Native name": "Avañe'ẽ",
    "639‑1": "gn",
    "639‑2/T": "grn",
    "639‑2/B": "grn",
    "639‑3": "grn + 5",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Gujarati",
    "Native name": "ગુજરાતી",
    "639‑1": "gu",
    "639‑2/T": "guj",
    "639‑2/B": "guj",
    "639‑3": "guj",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Creole",
    "Language name": "Haitian, Haitian Creole",
    "Native name": "Kreyòl ayisyen",
    "639‑1": "ht",
    "639‑2/T": "hat",
    "639‑2/B": "hat",
    "639‑3": "hat",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Afro-Asiatic",
    "Language name": "Hausa",
    "Native name": "(Hausa) هَوُسَ",
    "639‑1": "ha",
    "639‑2/T": "hau",
    "639‑2/B": "hau",
    "639‑3": "hau",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Afro-Asiatic",
    "Language name": "Hebrew (modern)",
    "Native name": "עברית",
    "639‑1": "he",
    "639‑2/T": "heb",
    "639‑2/B": "heb",
    "639‑3": "heb",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Herero",
    "Native name": "Otjiherero",
    "639‑1": "hz",
    "639‑2/T": "her",
    "639‑2/B": "her",
    "639‑3": "her",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Hindi",
    "Native name": "हिन्दी, हिंदी",
    "639‑1": "hi",
    "639‑2/T": "hin",
    "639‑2/B": "hin",
    "639‑3": "hin",
    "639‑6": "hins",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Hiri Motu",
    "Native name": "Hiri Motu",
    "639‑1": "ho",
    "639‑2/T": "hmo",
    "639‑2/B": "hmo",
    "639‑3": "hmo",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Uralic",
    "Language name": "Hungarian",
    "Native name": "magyar",
    "639‑1": "hu",
    "639‑2/T": "hun",
    "639‑2/B": "hun",
    "639‑3": "hun",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Constructed",
    "Language name": "Interlingua",
    "Native name": "Interlingua",
    "639‑1": "ia",
    "639‑2/T": "ina",
    "639‑2/B": "ina",
    "639‑3": "ina",
    "639‑6": 0,
    "Notes": "constructed by International Auxiliary Language Association",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Indonesian",
    "Native name": "Bahasa Indonesia",
    "639‑1": "id",
    "639‑2/T": "ind",
    "639‑2/B": "ind",
    "639‑3": "ind",
    "639‑6": 0,
    "Notes": "Covered by macrolanguage [ms/msa]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Constructed",
    "Language name": "Interlingue",
    "Native name": "Originally called Occidental; then Interlingue after WWII",
    "639‑1": "ie",
    "639‑2/T": "ile",
    "639‑2/B": "ile",
    "639‑3": "ile",
    "639‑6": 0,
    "Notes": "constructed by Edgar de Wahl, first published in 1922",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Irish",
    "Native name": "Gaeilge",
    "639‑1": "ga",
    "639‑2/T": "gle",
    "639‑2/B": "gle",
    "639‑3": "gle",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Igbo",
    "Native name": "Asụsụ Igbo",
    "639‑1": "ig",
    "639‑2/T": "ibo",
    "639‑2/B": "ibo",
    "639‑3": "ibo",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Eskimo–Aleut",
    "Language name": "Inupiaq",
    "Native name": "Iñupiaq, Iñupiatun",
    "639‑1": "ik",
    "639‑2/T": "ipk",
    "639‑2/B": "ipk",
    "639‑3": "ipk + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Constructed",
    "Language name": "Ido",
    "Native name": "Ido",
    "639‑1": "io",
    "639‑2/T": "ido",
    "639‑2/B": "ido",
    "639‑3": "ido",
    "639‑6": "idos",
    "Notes": "constructed by De Beaufront, 1907, as variation of Esperanto",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Icelandic",
    "Native name": "Íslenska",
    "639‑1": "is",
    "639‑2/T": "isl",
    "639‑2/B": "ice",
    "639‑3": "isl",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Italian",
    "Native name": "italiano",
    "639‑1": "it",
    "639‑2/T": "ita",
    "639‑2/B": "ita",
    "639‑3": "ita",
    "639‑6": "itas",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Eskimo–Aleut",
    "Language name": "Inuktitut",
    "Native name": "ᐃᓄᒃᑎᑐᑦ",
    "639‑1": "iu",
    "639‑2/T": "iku",
    "639‑2/B": "iku",
    "639‑3": "iku + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Japonic",
    "Language name": "Japanese",
    "Native name": "日本語 (にほんご)",
    "639‑1": "ja",
    "639‑2/T": "jpn",
    "639‑2/B": "jpn",
    "639‑3": "jpn",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Javanese",
    "Native name": "ꦧꦱꦗꦮ",
    "639‑1": "jv",
    "639‑2/T": "jav",
    "639‑2/B": "jav",
    "639‑3": "jav",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Eskimo–Aleut",
    "Language name": "Kalaallisut, Greenlandic",
    "Native name": "kalaallisut, kalaallit oqaasii",
    "639‑1": "kl",
    "639‑2/T": "kal",
    "639‑2/B": "kal",
    "639‑3": "kal",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Dravidian",
    "Language name": "Kannada",
    "Native name": "ಕನ್ನಡ",
    "639‑1": "kn",
    "639‑2/T": "kan",
    "639‑2/B": "kan",
    "639‑3": "kan",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Nilo-Saharan",
    "Language name": "Kanuri",
    "Native name": "Kanuri",
    "639‑1": "kr",
    "639‑2/T": "kau",
    "639‑2/B": "kau",
    "639‑3": "kau + 3",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Kashmiri",
    "Native name": "कश्मीरी, كشميري‎",
    "639‑1": "ks",
    "639‑2/T": "kas",
    "639‑2/B": "kas",
    "639‑3": "kas",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Kazakh",
    "Native name": "қазақ тілі",
    "639‑1": "kk",
    "639‑2/T": "kaz",
    "639‑2/B": "kaz",
    "639‑3": "kaz",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austroasiatic",
    "Language name": "Khmer",
    "Native name": "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ",
    "639‑1": "km",
    "639‑2/T": "khm",
    "639‑2/B": "khm",
    "639‑3": "khm",
    "639‑6": 0,
    "Notes": "a.k.a. Cambodian",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Kikuyu, Gikuyu",
    "Native name": "Gĩkũyũ",
    "639‑1": "ki",
    "639‑2/T": "kik",
    "639‑2/B": "kik",
    "639‑3": "kik",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Kinyarwanda",
    "Native name": "Ikinyarwanda",
    "639‑1": "rw",
    "639‑2/T": "kin",
    "639‑2/B": "kin",
    "639‑3": "kin",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Kyrgyz",
    "Native name": "Кыргызча, Кыргыз тили",
    "639‑1": "ky",
    "639‑2/T": "kir",
    "639‑2/B": "kir",
    "639‑3": "kir",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Uralic",
    "Language name": "Komi",
    "Native name": "коми кыв",
    "639‑1": "kv",
    "639‑2/T": "kom",
    "639‑2/B": "kom",
    "639‑3": "kom + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Kongo",
    "Native name": "Kikongo",
    "639‑1": "kg",
    "639‑2/T": "kon",
    "639‑2/B": "kon",
    "639‑3": "kon + 3",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Koreanic",
    "Language name": "Korean",
    "Native name": "한국어, 조선어",
    "639‑1": "ko",
    "639‑2/T": "kor",
    "639‑2/B": "kor",
    "639‑3": "kor",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Kurdish",
    "Native name": "Kurdî, كوردی‎",
    "639‑1": "ku",
    "639‑2/T": "kur",
    "639‑2/B": "kur",
    "639‑3": "kur + 3",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Kwanyama, Kuanyama",
    "Native name": "Kuanyama",
    "639‑1": "kj",
    "639‑2/T": "kua",
    "639‑2/B": "kua",
    "639‑3": "kua",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Latin",
    "Native name": "latine, lingua latina",
    "639‑1": "la",
    "639‑2/T": "lat",
    "639‑2/B": "lat",
    "639‑3": "lat",
    "639‑6": "lats",
    "Notes": "ancient",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Luxembourgish, Letzeburgesch",
    "Native name": "Lëtzebuergesch",
    "639‑1": "lb",
    "639‑2/T": "ltz",
    "639‑2/B": "ltz",
    "639‑3": "ltz",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Ganda",
    "Native name": "Luganda",
    "639‑1": "lg",
    "639‑2/T": "lug",
    "639‑2/B": "lug",
    "639‑3": "lug",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Limburgish, Limburgan, Limburger",
    "Native name": "Limburgs",
    "639‑1": "li",
    "639‑2/T": "lim",
    "639‑2/B": "lim",
    "639‑3": "lim",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Lingala",
    "Native name": "Lingála",
    "639‑1": "ln",
    "639‑2/T": "lin",
    "639‑2/B": "lin",
    "639‑3": "lin",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Tai–Kadai",
    "Language name": "Lao",
    "Native name": "ພາສາລາວ",
    "639‑1": "lo",
    "639‑2/T": "lao",
    "639‑2/B": "lao",
    "639‑3": "lao",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Lithuanian",
    "Native name": "lietuvių kalba",
    "639‑1": "lt",
    "639‑2/T": "lit",
    "639‑2/B": "lit",
    "639‑3": "lit",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Luba-Katanga",
    "Native name": "Tshiluba",
    "639‑1": "lu",
    "639‑2/T": "lub",
    "639‑2/B": "lub",
    "639‑3": "lub",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Latvian",
    "Native name": "latviešu valoda",
    "639‑1": "lv",
    "639‑2/T": "lav",
    "639‑2/B": "lav",
    "639‑3": "lav + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Manx",
    "Native name": "Gaelg, Gailck",
    "639‑1": "gv",
    "639‑2/T": "glv",
    "639‑2/B": "glv",
    "639‑3": "glv",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Macedonian",
    "Native name": "македонски јазик",
    "639‑1": "mk",
    "639‑2/T": "mkd",
    "639‑2/B": "mac",
    "639‑3": "mkd",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Malagasy",
    "Native name": "fiteny malagasy",
    "639‑1": "mg",
    "639‑2/T": "mlg",
    "639‑2/B": "mlg",
    "639‑3": "mlg +10",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Malay",
    "Native name": "bahasa Melayu, بهاس ملايو‎",
    "639‑1": "ms",
    "639‑2/T": "msa",
    "639‑2/B": "may",
    "639‑3": "msa +13",
    "639‑6": 0,
    "Notes": "macrolanguage, Standard Malay is [zsm], Indonesianis [id/ind]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Dravidian",
    "Language name": "Malayalam",
    "Native name": "മലയാളം",
    "639‑1": "ml",
    "639‑2/T": "mal",
    "639‑2/B": "mal",
    "639‑3": "mal",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Afro-Asiatic",
    "Language name": "Maltese",
    "Native name": "Malti",
    "639‑1": "mt",
    "639‑2/T": "mlt",
    "639‑2/B": "mlt",
    "639‑3": "mlt",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Māori",
    "Native name": "te reo Māori",
    "639‑1": "mi",
    "639‑2/T": "mri",
    "639‑2/B": "mao",
    "639‑3": "mri",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Marathi (Marāṭhī)",
    "Native name": "मराठी",
    "639‑1": "mr",
    "639‑2/T": "mar",
    "639‑2/B": "mar",
    "639‑3": "mar",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Marshallese",
    "Native name": "Kajin M̧ajeļ",
    "639‑1": "mh",
    "639‑2/T": "mah",
    "639‑2/B": "mah",
    "639‑3": "mah",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Mongolic",
    "Language name": "Mongolian",
    "Native name": "Монгол хэл",
    "639‑1": "mn",
    "639‑2/T": "mon",
    "639‑2/B": "mon",
    "639‑3": "mon + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Nauruan",
    "Native name": "Dorerin Naoero",
    "639‑1": "na",
    "639‑2/T": "nau",
    "639‑2/B": "nau",
    "639‑3": "nau",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Dené–Yeniseian",
    "Language name": "Navajo, Navaho",
    "Native name": "Diné bizaad",
    "639‑1": "nv",
    "639‑2/T": "nav",
    "639‑2/B": "nav",
    "639‑3": "nav",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Northern Ndebele",
    "Native name": "isiNdebele",
    "639‑1": "nd",
    "639‑2/T": "nde",
    "639‑2/B": "nde",
    "639‑3": "nde",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Nepali",
    "Native name": "नेपाली",
    "639‑1": "ne",
    "639‑2/T": "nep",
    "639‑2/B": "nep",
    "639‑3": "nep",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Ndonga",
    "Native name": "Owambo",
    "639‑1": "ng",
    "639‑2/T": "ndo",
    "639‑2/B": "ndo",
    "639‑3": "ndo",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Norwegian Bokmål",
    "Native name": "Norsk bokmål",
    "639‑1": "nb",
    "639‑2/T": "nob",
    "639‑2/B": "nob",
    "639‑3": "nob",
    "639‑6": 0,
    "Notes": "Covered by macrolanguage [no/nor]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Norwegian Nynorsk",
    "Native name": "Norsk nynorsk",
    "639‑1": "nn",
    "639‑2/T": "nno",
    "639‑2/B": "nno",
    "639‑3": "nno",
    "639‑6": 0,
    "Notes": "Covered by macrolanguage [no/nor]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Norwegian",
    "Native name": "Norsk",
    "639‑1": "no",
    "639‑2/T": "nor",
    "639‑2/B": "nor",
    "639‑3": "nor + 2",
    "639‑6": 0,
    "Notes": "macrolanguage, Bokmål is [nb/nob], Nynorsk is [nn/nno]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Sino-Tibetan",
    "Language name": "Nuosu",
    "Native name": "ꆈꌠ꒿ Nuosuhxop",
    "639‑1": "ii",
    "639‑2/T": "iii",
    "639‑2/B": "iii",
    "639‑3": "iii",
    "639‑6": 0,
    "Notes": "Standard form of Yi languages",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Southern Ndebele",
    "Native name": "isiNdebele",
    "639‑1": "nr",
    "639‑2/T": "nbl",
    "639‑2/B": "nbl",
    "639‑3": "nbl",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Occitan",
    "Native name": "occitan, lenga d'òc",
    "639‑1": "oc",
    "639‑2/T": "oci",
    "639‑2/B": "oci",
    "639‑3": "oci",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Algonquian",
    "Language name": "Ojibwe, Ojibwa",
    "Native name": "ᐊᓂᔑᓈᐯᒧᐎᓐ",
    "639‑1": "oj",
    "639‑2/T": "oji",
    "639‑2/B": "oji",
    "639‑3": "oji + 7",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Old Church Slavonic, Church Slavonic, Old Bulgarian",
    "Native name": "ѩзыкъ словѣньскъ",
    "639‑1": "cu",
    "639‑2/T": "chu",
    "639‑2/B": "chu",
    "639‑3": "chu",
    "639‑6": 0,
    "Notes": "ancient, in use by Orthodox Church",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Afro-Asiatic",
    "Language name": "Oromo",
    "Native name": "Afaan Oromoo",
    "639‑1": "om",
    "639‑2/T": "orm",
    "639‑2/B": "orm",
    "639‑3": "orm + 4",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Oriya",
    "Native name": "ଓଡ଼ିଆ",
    "639‑1": "or",
    "639‑2/T": "ori",
    "639‑2/B": "ori",
    "639‑3": "ori",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Ossetian, Ossetic",
    "Native name": "ирон æвзаг",
    "639‑1": "os",
    "639‑2/T": "oss",
    "639‑2/B": "oss",
    "639‑3": "oss",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Panjabi, Punjabi",
    "Native name": "ਪੰਜਾਬੀ, پنجابی‎",
    "639‑1": "pa",
    "639‑2/T": "pan",
    "639‑2/B": "pan",
    "639‑3": "pan",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Pāli",
    "Native name": "पाऴि",
    "639‑1": "pi",
    "639‑2/T": "pli",
    "639‑2/B": "pli",
    "639‑3": "pli",
    "639‑6": 0,
    "Notes": "ancient",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Persian (Farsi)",
    "Native name": "فارسی",
    "639‑1": "fa",
    "639‑2/T": "fas",
    "639‑2/B": "per",
    "639‑3": "fas + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Polish",
    "Native name": "język polski, polszczyzna",
    "639‑1": "pl",
    "639‑2/T": "pol",
    "639‑2/B": "pol",
    "639‑3": "pol",
    "639‑6": "pols",
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Pashto, Pushto",
    "Native name": "پښتو",
    "639‑1": "ps",
    "639‑2/T": "pus",
    "639‑2/B": "pus",
    "639‑3": "pus + 3",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Portuguese",
    "Native name": "português",
    "639‑1": "pt",
    "639‑2/T": "por",
    "639‑2/B": "por",
    "639‑3": "por",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Quechuan",
    "Language name": "Quechua",
    "Native name": "Runa Simi, Kichwa",
    "639‑1": "qu",
    "639‑2/T": "que",
    "639‑2/B": "que",
    "639‑3": "que +44",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Romansh",
    "Native name": "rumantsch grischun",
    "639‑1": "rm",
    "639‑2/T": "roh",
    "639‑2/B": "roh",
    "639‑3": "roh",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Kirundi",
    "Native name": "Ikirundi",
    "639‑1": "rn",
    "639‑2/T": "run",
    "639‑2/B": "run",
    "639‑3": "run",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Creole",
    "Language name": "Reunionese, Reunion Creole",
    "Native name": "Kréol Rénioné",
    "639‑1": "rc",
    "639‑2/T": "rcf",
    "639‑2/B": "rcf",
    "639‑3": "rcf",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Romanian",
    "Native name": "limba română",
    "639‑1": "ro",
    "639‑2/T": "ron",
    "639‑2/B": "rum",
    "639‑3": "ron",
    "639‑6": 0,
    "Notes": "[mo] for Moldavian has been withdrawn, recommending [ro] also for Moldavian",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Russian",
    "Native name": "Русский",
    "639‑1": "ru",
    "639‑2/T": "rus",
    "639‑2/B": "rus",
    "639‑3": "rus",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Sanskrit (Saṁskṛta)",
    "Native name": "संस्कृतम्",
    "639‑1": "sa",
    "639‑2/T": "san",
    "639‑2/B": "san",
    "639‑3": "san",
    "639‑6": 0,
    "Notes": "ancient, still spoken",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Sardinian",
    "Native name": "sardu",
    "639‑1": "sc",
    "639‑2/T": "srd",
    "639‑2/B": "srd",
    "639‑3": "srd + 4",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Sindhi",
    "Native name": "सिन्धी, سنڌي، سندھی‎",
    "639‑1": "sd",
    "639‑2/T": "snd",
    "639‑2/B": "snd",
    "639‑3": "snd",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Uralic",
    "Language name": "Northern Sami",
    "Native name": "Davvisámegiella",
    "639‑1": "se",
    "639‑2/T": "sme",
    "639‑2/B": "sme",
    "639‑3": "sme",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Samoan",
    "Native name": "gagana fa'a Samoa",
    "639‑1": "sm",
    "639‑2/T": "smo",
    "639‑2/B": "smo",
    "639‑3": "smo",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Creole",
    "Language name": "Sango",
    "Native name": "yângâ tî sängö",
    "639‑1": "sg",
    "639‑2/T": "sag",
    "639‑2/B": "sag",
    "639‑3": "sag",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Serbian",
    "Native name": "српски језик",
    "639‑1": "sr",
    "639‑2/T": "srp",
    "639‑2/B": "srp",
    "639‑3": "srp",
    "639‑6": 0,
    "Notes": "The ISO 639-2/T code srp deprecated the ISO 639-2/B code scc[1]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Scottish Gaelic, Gaelic",
    "Native name": "Gàidhlig",
    "639‑1": "gd",
    "639‑2/T": "gla",
    "639‑2/B": "gla",
    "639‑3": "gla",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Shona",
    "Native name": "chiShona",
    "639‑1": "sn",
    "639‑2/T": "sna",
    "639‑2/B": "sna",
    "639‑3": "sna",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Sinhalese, Sinhala",
    "Native name": "සිංහල",
    "639‑1": "si",
    "639‑2/T": "sin",
    "639‑2/B": "sin",
    "639‑3": "sin",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Slovak",
    "Native name": "slovenčina, slovenský jazyk",
    "639‑1": "sk",
    "639‑2/T": "slk",
    "639‑2/B": "slo",
    "639‑3": "slk",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Slovene",
    "Native name": "slovenski jezik, slovenščina",
    "639‑1": "sl",
    "639‑2/T": "slv",
    "639‑2/B": "slv",
    "639‑3": "slv",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Afro-Asiatic",
    "Language name": "Somali",
    "Native name": "Soomaaliga, af Soomaali",
    "639‑1": "so",
    "639‑2/T": "som",
    "639‑2/B": "som",
    "639‑3": "som",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Southern Sotho",
    "Native name": "Sesotho",
    "639‑1": "st",
    "639‑2/T": "sot",
    "639‑2/B": "sot",
    "639‑3": "sot",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Spanish",
    "Native name": "español",
    "639‑1": "es",
    "639‑2/T": "spa",
    "639‑2/B": "spa",
    "639‑3": "spa",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Sundanese",
    "Native name": "Basa Sunda",
    "639‑1": "su",
    "639‑2/T": "sun",
    "639‑2/B": "sun",
    "639‑3": "sun",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Swahili",
    "Native name": "Kiswahili",
    "639‑1": "sw",
    "639‑2/T": "swa",
    "639‑2/B": "swa",
    "639‑3": "swa + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Swati",
    "Native name": "SiSwati",
    "639‑1": "ss",
    "639‑2/T": "ssw",
    "639‑2/B": "ssw",
    "639‑3": "ssw",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Swedish",
    "Native name": "svenska",
    "639‑1": "sv",
    "639‑2/T": "swe",
    "639‑2/B": "swe",
    "639‑3": "swe",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Dravidian",
    "Language name": "Tamil",
    "Native name": "தமிழ்",
    "639‑1": "ta",
    "639‑2/T": "tam",
    "639‑2/B": "tam",
    "639‑3": "tam",
    "639‑6": 0,
    "Notes": "Ancient, Still spoken",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Dravidian",
    "Language name": "Telugu",
    "Native name": "తెలుగు",
    "639‑1": "te",
    "639‑2/T": "tel",
    "639‑2/B": "tel",
    "639‑3": "tel",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Tajik",
    "Native name": "тоҷикӣ, toçikī, تاجیکی‎",
    "639‑1": "tg",
    "639‑2/T": "tgk",
    "639‑2/B": "tgk",
    "639‑3": "tgk",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Tai–Kadai",
    "Language name": "Thai",
    "Native name": "ไทย",
    "639‑1": "th",
    "639‑2/T": "tha",
    "639‑2/B": "tha",
    "639‑3": "tha",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Afro-Asiatic",
    "Language name": "Tigrinya",
    "Native name": "ትግርኛ",
    "639‑1": "ti",
    "639‑2/T": "tir",
    "639‑2/B": "tir",
    "639‑3": "tir",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Sino-Tibetan",
    "Language name": "Tibetan Standard, Tibetan, Central",
    "Native name": "བོད་ཡིག",
    "639‑1": "bo",
    "639‑2/T": "bod",
    "639‑2/B": "tib",
    "639‑3": "bod",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Turkmen",
    "Native name": "Türkmen, Түркмен",
    "639‑1": "tk",
    "639‑2/T": "tuk",
    "639‑2/B": "tuk",
    "639‑3": "tuk",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Tagalog",
    "Native name": "Wikang Tagalog",
    "639‑1": "tl",
    "639‑2/T": "tgl",
    "639‑2/B": "tgl",
    "639‑3": "tgl",
    "639‑6": 0,
    "Notes": "Note: Filipino (Pilipino) has the code [fil]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Tswana",
    "Native name": "Setswana",
    "639‑1": "tn",
    "639‑2/T": "tsn",
    "639‑2/B": "tsn",
    "639‑3": "tsn",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Tonga (Tonga Islands)",
    "Native name": "faka Tonga",
    "639‑1": "to",
    "639‑2/T": "ton",
    "639‑2/B": "ton",
    "639‑3": "ton",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Turkish",
    "Native name": "Türkçe",
    "639‑1": "tr",
    "639‑2/T": "tur",
    "639‑2/B": "tur",
    "639‑3": "tur",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Tsonga",
    "Native name": "Xitsonga",
    "639‑1": "ts",
    "639‑2/T": "tso",
    "639‑2/B": "tso",
    "639‑3": "tso",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Tatar",
    "Native name": "татар теле, tatar tele",
    "639‑1": "tt",
    "639‑2/T": "tat",
    "639‑2/B": "tat",
    "639‑3": "tat",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Twi",
    "Native name": "Twi",
    "639‑1": "tw",
    "639‑2/T": "twi",
    "639‑2/B": "twi",
    "639‑3": "twi",
    "639‑6": 0,
    "Notes": "Covered by macrolanguage [ak/aka]",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austronesian",
    "Language name": "Tahitian",
    "Native name": "Reo Tahiti",
    "639‑1": "ty",
    "639‑2/T": "tah",
    "639‑2/B": "tah",
    "639‑3": "tah",
    "639‑6": 0,
    "Notes": "One of the Reo Mā`ohi (languages of French Polynesia)",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Uyghur",
    "Native name": "ئۇيغۇرچە‎, Uyghurche",
    "639‑1": "ug",
    "639‑2/T": "uig",
    "639‑2/B": "uig",
    "639‑3": "uig",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Ukrainian",
    "Native name": "Українська",
    "639‑1": "uk",
    "639‑2/T": "ukr",
    "639‑2/B": "ukr",
    "639‑3": "ukr",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Urdu",
    "Native name": "اردو",
    "639‑1": "ur",
    "639‑2/T": "urd",
    "639‑2/B": "urd",
    "639‑3": "urd",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Turkic",
    "Language name": "Uzbek",
    "Native name": "Oʻzbek, Ўзбек, أۇزبېك‎",
    "639‑1": "uz",
    "639‑2/T": "uzb",
    "639‑2/B": "uzb",
    "639‑3": "uzb + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Venda",
    "Native name": "Tshivenḓa",
    "639‑1": "ve",
    "639‑2/T": "ven",
    "639‑2/B": "ven",
    "639‑3": "ven",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Austroasiatic",
    "Language name": "Vietnamese",
    "Native name": "Tiếng Việt",
    "639‑1": "vi",
    "639‑2/T": "vie",
    "639‑2/B": "vie",
    "639‑3": "vie",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Constructed",
    "Language name": "Volapük",
    "Native name": "Volapük",
    "639‑1": "vo",
    "639‑2/T": "vol",
    "639‑2/B": "vol",
    "639‑3": "vol",
    "639‑6": 0,
    "Notes": "constructed",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Walloon",
    "Native name": "walon",
    "639‑1": "wa",
    "639‑2/T": "wln",
    "639‑2/B": "wln",
    "639‑3": "wln",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Welsh",
    "Native name": "Cymraeg",
    "639‑1": "cy",
    "639‑2/T": "cym",
    "639‑2/B": "wel",
    "639‑3": "cym",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Wolof",
    "Native name": "Wollof",
    "639‑1": "wo",
    "639‑2/T": "wol",
    "639‑2/B": "wol",
    "639‑3": "wol",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Western Frisian",
    "Native name": "Frysk",
    "639‑1": "fy",
    "639‑2/T": "fry",
    "639‑2/B": "fry",
    "639‑3": "fry",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Xhosa",
    "Native name": "isiXhosa",
    "639‑1": "xh",
    "639‑2/T": "xho",
    "639‑2/B": "xho",
    "639‑3": "xho",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Indo-European",
    "Language name": "Yiddish",
    "Native name": "ייִדיש",
    "639‑1": "yi",
    "639‑2/T": "yid",
    "639‑2/B": "yid",
    "639‑3": "yid + 2",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Yoruba",
    "Native name": "Yorùbá",
    "639‑1": "yo",
    "639‑2/T": "yor",
    "639‑2/B": "yor",
    "639‑3": "yor",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Tai–Kadai",
    "Language name": "Zhuang, Chuang",
    "Native name": "Saɯ cueŋƅ, Saw cuengh",
    "639‑1": "za",
    "639‑2/T": "zha",
    "639‑2/B": "zha",
    "639‑3": "zha +16",
    "639‑6": 0,
    "Notes": "macrolanguage",
    "": 0
  },
  {
    "blank": 0,
    "Language family": "Niger–Congo",
    "Language name": "Zulu",
    "Native name": "isiZulu",
    "639‑1": "zu",
    "639‑2/T": "zul",
    "639‑2/B": "zul",
    "639‑3": "zul",
    "639‑6": 0,
    "Notes": 0,
    "": 0
  }
]

export {
  languages_iso_639
}